//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace App.Common {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppCommon {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppCommon() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("App.Common.AppCommon", typeof(AppCommon).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;{0}&quot; cannot be empty..
        /// </summary>
        internal static string Argument_Cannot_Be_Empty {
            get {
                return ResourceManager.GetString("Argument_Cannot_Be_Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;{0}&quot; cannot be empty guid..
        /// </summary>
        internal static string Argument_Cannot_Be_Empty_Guid {
            get {
                return ResourceManager.GetString("Argument_Cannot_Be_Empty_Guid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;{0}&quot; cannot be more than {1} character..
        /// </summary>
        internal static string Argument_Out_of_Length {
            get {
                return ResourceManager.GetString("Argument_Out_of_Length", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Collection cannot be empty..
        /// </summary>
        internal static string Collection_Cannot_Be_Empty {
            get {
                return ResourceManager.GetString("Collection_Cannot_Be_Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File with the name {0} is not found..
        /// </summary>
        internal static string File_Not_Found {
            get {
                return ResourceManager.GetString("File_Not_Found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can not read file {0}..
        /// </summary>
        internal static string File_Read_Error {
            get {
                return ResourceManager.GetString("File_Read_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File {0} exceeds the maximum size allowed..
        /// </summary>
        internal static string File_Size_Too_Large {
            get {
                return ResourceManager.GetString("File_Size_Too_Large", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect type, it must be descended of &quot;{0}&quot;..
        /// </summary>
        internal static string IncorrectTypeMustBeDescended {
            get {
                return ResourceManager.GetString("IncorrectTypeMustBeDescended", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid boolean attribute {0}..
        /// </summary>
        internal static string Invalid_Bool_Attr {
            get {
                return ResourceManager.GetString("Invalid_Bool_Attr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Command ID: {0}..
        /// </summary>
        internal static string Invalid_Command_Id {
            get {
                return ResourceManager.GetString("Invalid_Command_Id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;{0}&quot; is not a valid email address..
        /// </summary>
        internal static string Invalid_Email_Address {
            get {
                return ResourceManager.GetString("Invalid_Email_Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid integer attribute {0}..
        /// </summary>
        internal static string Invalid_Integer_Attr {
            get {
                return ResourceManager.GetString("Invalid_Integer_Attr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid positive integer attribute {0}..
        /// </summary>
        internal static string Invalid_Positive_Integer_Attr {
            get {
                return ResourceManager.GetString("Invalid_Positive_Integer_Attr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid type attribute {0}..
        /// </summary>
        internal static string Invalid_Type_Attr {
            get {
                return ResourceManager.GetString("Invalid_Type_Attr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;{0}&quot; is not a valid web url..
        /// </summary>
        internal static string Invalid_Web_Url {
            get {
                return ResourceManager.GetString("Invalid_Web_Url", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} must be between &quot;{1}&quot;-&quot;{2}&quot;..
        /// </summary>
        internal static string Length_Must_Be_In_Range {
            get {
                return ResourceManager.GetString("Length_Must_Be_In_Range", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No child nodes..
        /// </summary>
        internal static string No_Child_Nodes {
            get {
                return ResourceManager.GetString("No_Child_Nodes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Node {0} missing required attribute {1}..
        /// </summary>
        internal static string Node_Missing_Required_Attr {
            get {
                return ResourceManager.GetString("Node_Missing_Required_Attr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Node type is not element..
        /// </summary>
        internal static string Node_Type_Is_Not_Element {
            get {
                return ResourceManager.GetString("Node_Type_Is_Not_Element", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Required attribute {0} can not be empty..
        /// </summary>
        internal static string Required_Attr_Can_Not_Be_Empty {
            get {
                return ResourceManager.GetString("Required_Attr_Can_Not_Be_Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Required attribute {0} is missing..
        /// </summary>
        internal static string Required_Attr_Missing {
            get {
                return ResourceManager.GetString("Required_Attr_Missing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unrecognized_attribute {0}..
        /// </summary>
        internal static string Unrecognized_Attr {
            get {
                return ResourceManager.GetString("Unrecognized_Attr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unrecognized element..
        /// </summary>
        internal static string Unrecognized_Element {
            get {
                return ResourceManager.GetString("Unrecognized_Element", resourceCulture);
            }
        }
    }
}
